171/implement a consistent layout for the homepage and resultpage for the webversion
hochschule-darmstadt/einander-helfen pull request #177
Opened 2020-11-23 15:18 UTC by MaiThiD

2020-11-23 16:45 UTC, FiedlerJan requested changes
Looks good, but still has some small things that should be changed.

2020-11-23 16:45 UTC, FiedlerJan commented on app/src/views/Home.vue
> +          <!-- v-col cols="12" md="8"-->
Please remove commented code.

2020-11-23 16:45 UTC, FiedlerJan commented on app/src/views/Home.vue
> +}
Please use correct indents.

2020-11-23 16:45 UTC, FiedlerJan commented on app/src/views/ResultPage.vue
> +}
Please use correct indents.

2020-11-23 21:02 UTC, FiedlerJan approved these changes

2020-11-24 19:20 UTC, LeDrieHda approved these changes
From the viewpoint of functional architect:
UI on home page and result page is consistent in that they have the same margin left and right.
Result page has implemented the proposed and discussed changes and its design is now overall more appealing to the user.

2020-11-25 12:06 UTC, DianaPankratz approved these changes

2020-11-25 14:12 UTC, merged