169/proposal for new crawling website int
hochschule-darmstadt/einander-helfen pull request #192
Opened 2020-11-30 19:17 UTC by DanielKraft

You can test it with the following commands:

```shell
$ cd etl
$ python (or python3)
>>> from data_extraction.scraper.weltwaerts import WeltwaertsScraper as ww
>>> i = ww('test')
>>> i.add_urls()
(approx. 11 min)

>>> i.crawl(i.urls[0], 1)
>>> i.data
```

2020-11-30 19:23 UTC, MaiThiD reviewed
"We have decided to leave out logos. So:

1.	Remove from data model
2.	Do not set in backend"(https://github.com/hochschule-darmstadt/einander-helfen/issues/189#issuecomment-735798346)

2020-11-30 19:38 UTC, DanielKraft commented
> "We have decided to leave out logos. So:
> 
> 1.	Remove from data model
> 2.	Do not set in backend"(https://github.com/hochschule-darmstadt/einander-helfen/issues/189#issuecomment-735798346)
> 

Done.

2020-11-30 20:08 UTC, FiedlerJan requested changes
I got same more things you should take a look on:

- Please write the class and function description in a docstring format ("""description""")
- Why are there so many errors due to duplicated links?

2020-11-30 20:08 UTC, FiedlerJan commented on etl/data_extraction/scraper/weltwaerts.py
> +            response = self.soupify(next_page_url)
Currently you have only 10 results per page. The page gives you an option to scrape up to 50 results per page. This is possible by sending this arument with the request. Is there a possible implementation? (Maybe by overloading the soupify method which takes and request argument)
![grafik](https://user-images.githubusercontent.com/64203299/100658645-b4948f80-334f-11eb-90d4-5d74551d0738.png)

2020-11-30 20:24 UTC, DanielKraft commented on etl/data_extraction/scraper/weltwaerts.py
> +        while next_page_url:
The maximum number of pages is not necessary for our implementation.
What is the advantage of using the maximum number of pages?

2020-11-30 22:52 UTC, DanielKraft commented
> * Why are there so many errors due to duplicated links?

For some reason sometimes entries are listed twice. The error is not due to the crawler, but to weltwärts.de

2020-11-30 23:01 UTC, FiedlerJan commented on etl/data_extraction/scraper/weltwaerts.py
> +        while next_page_url:
I think there is no direct advantage. Only thing is that the debugging is more obvious (f.e. 4/567).

2020-11-30 23:06 UTC, DanielKraft commented on etl/data_extraction/scraper/weltwaerts.py
> +        while next_page_url:
I have added the maximum number of pages to the debug message.

2020-12-02 19:46 UTC, FiedlerJan requested changes
Sorry for the late review. I crawled the whole page. During this I found one reoccurring mistake. Somewhere during the crawling process an index is out of range.

```
{
        "fn": "parse",
        "body": "list index out of range",
        "index": 3361,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201020"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3362,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201021"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3363,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201024"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3378,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201023"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3379,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=209700"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3423,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201025"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3435,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201026"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3485,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=209699"
    },
    {
        "fn": "parse",
        "body": "list index out of range",
        "index": 3512,
        "url": "https://www.weltwaerts.de/de/ep-detail.html?id=201019"
    }
```

Please take a look on this.

2020-12-03 10:43 UTC, FiedlerJan approved these changes

2020-12-03 14:54 UTC, MaiThiD approved these changes

2020-12-03 16:05 UTC, jonas-hda approved these changes

2020-12-03 16:06 UTC, merged