61/homepage responsiveness for mobile devices
hochschule-darmstadt/einander-helfen pull request #223
Opened 2020-12-08 18:01 UTC by MaiThiD

This PR solves #222 #61 #220

2020-12-08 20:07 UTC, DianaPankratz requested changes
When the screen width is around 285 px the burgermenu overlaps the text. I think the text should disapear when the screen width is below 300px instead of 283px
![Unbenannt](https://user-images.githubusercontent.com/73997936/101535328-c8b43e80-3998-11eb-98e6-7c4d9896a2ae.PNG)

When focussing the input element on the page there es no space between the element and the top of the screen. There should be a little Padding. Instead of using `focussearch.scrollIntoView(true);` you could use something like: 
```
if (focussearch!= null) {
          const headerOffset = 10;
          const elementPosition = focussearch.getBoundingClientRect().top;
          const offsetPosition = elementPosition - headerOffset;
          window.scrollTo({top: offsetPosition});
```

2020-12-09 12:17 UTC, DianaPankratz approved these changes

2020-12-09 12:37 UTC, FiedlerJan approved these changes

2020-12-10 09:42 UTC, LeDrieHda approved these changes

2020-12-10 10:16 UTC, merged