216 Added crawler for ein-jahr-freiwillig.de
hochschule-darmstadt/einander-helfen pull request #230
Opened 2020-12-10 15:32 UTC by AndreBruecke

Crawler implementation for ein-jahr-freiwillig.de

Can be tested with the following commands:

```
$ cd etl
$ python (or python3)
>>> from data_extraction.scraper.ein_jahr_freiwillig import EinJahrFreiwillig as scr
>>> i = scr('test')
>>> i.add_urls()

>>> i.crawl(i.urls[0], 1)
>>> i.data
```

2020-12-12 16:19 UTC, FiedlerJan requested changes
I tested it with some random urls. The task is always null.

Here the urls I tested:
```
>>> for j in range(0, 20):
...    i.crawl(i.urls[j], randrange(len(i.urls)))
... 
[test] Scraping page #9646 [9646/16381]
[test] Scraping page #9646 ended
[test] Scraping page #8576 [8576/16381]
[test] Scraping page #8576 ended
[test] Scraping page #9192 [9192/16381]
[test] Scraping page #9192 ended
[test] Scraping page #6013 [6013/16381]
[test] Scraping page #6013 ended
[test] Scraping page #980 [980/16381]
[test] Scraping page #980 ended
[test] Scraping page #13084 [13084/16381]
[test] Scraping page #13084 ended
[test] Scraping page #1614 [1614/16381]
[test] Scraping page #1614 ended
[test] Scraping page #3205 [3205/16381]
[test] Scraping page #3205 ended
[test] Scraping page #12807 [12807/16381]
[test] Scraping page #12807 ended
[test] Scraping page #14048 [14048/16381]
[test] Scraping page #14048 ended
[test] Scraping page #10928 [10928/16381]
[test] Scraping page #10928 ended
[test] Scraping page #8662 [8662/16381]
[test] Scraping page #8662 ended
[test] Scraping page #3487 [3487/16381]
[test] Scraping page #3487 ended
[test] Scraping page #8298 [8298/16381]
[test] Scraping page #8298 ended
[test] Scraping page #7887 [7887/16381]
[test] Scraping page #7887 ended
[test] Scraping page #1950 [1950/16381]
[test] Scraping page #1950 ended
[test] Scraping page #7084 [7084/16381]
[test] Scraping page #7084 ended
[test] Scraping page #10400 [10400/16381]
[test] Scraping page #10400 ended
[test] Scraping page #15576 [15576/16381]
[test] Scraping page #15576 ended
[test] Scraping page #9283 [9283/16381]
[test] Scraping page #9283 ended
```

2020-12-12 16:34 UTC, DanielKraft commented
Can you send me the links of the posts to find out if it is a mistake. On the website not all posts have an entry at Task.

2020-12-12 22:46 UTC, FiedlerJan approved these changes

2020-12-13 13:14 UTC, jonas-hda approved these changes

2020-12-13 13:14 UTC, merged