#221 set stage.page = 1
hochschule-darmstadt/einander-helfen pull request #231
Opened 2020-12-10 16:30 UTC by MaiThiD

2020-12-10 22:49 UTC, FiedlerJan requested changes
This does not work if you search for an existing tag with more than one result.

What is not working:
1. Search without tags (724 result)
2. Got to the last page (this is not even necessary)
3. Go to 'home'
4. enter 'help' and start the search
5. The result page shows you all 724 pages
6. Make a reload of the page
7. No results are displayed (as expected)

2020-12-10 23:48 UTC, FiedlerJan approved these changes
https://github.com/hochschule-darmstadt/einander-helfen/pull/231#pullrequestreview-549670709

Guess this has to be done by another issue (and PR).

2020-12-10 23:58 UTC, MaiThiD commented
> [#231 (review)](https://github.com/hochschule-darmstadt/einander-helfen/pull/231#pullrequestreview-549670709)
> 
> Guess this has to be done by another issue (and PR).

This behaviour occurs because of the missing geolocation which will be fixed in #215

2020-12-11 13:21 UTC, DianaPankratz approved these changes

2020-12-12 13:54 UTC, LeDrieHda approved these changes

2020-12-12 14:34 UTC, merged