#218 removed unneccessary content in subtitle
hochschule-darmstadt/einander-helfen pull request #233
Opened 2020-12-10 21:37 UTC by MaiThiD

2020-12-10 22:54 UTC, FiedlerJan reviewed
I'm not sure, but didn't we say that the 'post_struct' may be accessed for this display? That would make the code in the frontend easier and there would be no unnecessary commas. @BernhardHumm

2020-12-11 12:15 UTC, BernhardHumm commented
I don’t understand what this issue is about.

 

 

 

 

Von: JanF <notifications@github.com> 
Gesendet: Donnerstag, 10. Dezember 2020 23:54
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com>
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de>; Mention <mention@noreply.github.com>
Betreff: Re: [hochschule-darmstadt/einander-helfen] #218 removed unneccessary content in subtitle (#233)

 

@FiedlerJan commented on this pull request.

I'm not sure, but didn't we say that the 'post_struct' may be accessed for this display? That would make the code in the frontend easier and there would be no unnecessary commas. @BernhardHumm <https://github.com/BernhardHumm> 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/hochschule-darmstadt/einander-helfen/pull/233#pullrequestreview-549676656> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABYWHS3C755SMZCBRNZSPVLSUFGRPANCNFSM4UVUNT2A> .  <https://github.com/notifications/beacon/ABYWHSZ5OMCJT6VXDQKJZE3SUFGRPA5CNFSM4UVUNT2KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEDBWM4A.gif>

2020-12-11 12:54 UTC, FiedlerJan commented
> I don’t understand what this issue is about.

Please take a look at #218.

2020-12-11 13:11 UTC, DianaPankratz approved these changes

2020-12-11 13:41 UTC, BernhardHumm commented
Yes, use the structured information from location (which should only contain content from the original post). Use the following attributes if existing:

Zip code

City

Country

 

For national posts, it will presumably be City or Zip code + City, for international posts presumably City + Country.

 

 

Von: Humm, Bernhard, Prof. Dr. 
Gesendet: Freitag, 11. Dezember 2020 13:16
An: 'hochschule-darmstadt/einander-helfen' <reply@reply.github.com>
Betreff: AW: [hochschule-darmstadt/einander-helfen] #218 removed unneccessary content in subtitle (#233)

 

I don’t understand what this issue is about.

 

 

 

 

Von: JanF <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Donnerstag, 10. Dezember 2020 23:54
An: hochschule-darmstadt/einander-helfen <einander-helfen@noreply.github.com <mailto:einander-helfen@noreply.github.com> >
Cc: Humm, Bernhard, Prof. Dr. <bernhard.humm@h-da.de <mailto:bernhard.humm@h-da.de> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Betreff: Re: [hochschule-darmstadt/einander-helfen] #218 removed unneccessary content in subtitle (#233)

 

@FiedlerJan commented on this pull request.

I'm not sure, but didn't we say that the 'post_struct' may be accessed for this display? That would make the code in the frontend easier and there would be no unnecessary commas. @BernhardHumm <https://github.com/BernhardHumm> 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub <https://github.com/hochschule-darmstadt/einander-helfen/pull/233#pullrequestreview-549676656> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/ABYWHS3C755SMZCBRNZSPVLSUFGRPANCNFSM4UVUNT2A> .  <https://github.com/notifications/beacon/ABYWHSZ5OMCJT6VXDQKJZE3SUFGRPA5CNFSM4UVUNT2KYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOEDBWM4A.gif>

2020-12-11 17:23 UTC, FiedlerJan requested changes

2020-12-11 17:23 UTC, FiedlerJan commented on app/src/views/ResultPage.vue
> +                        <span> {{post.post_struct.location.city}}</span>
Please add the post_struct with country, city and zipcode to the post.ts model.

2020-12-11 17:47 UTC, FiedlerJan approved these changes

2020-12-12 13:56 UTC, LeDrieHda approved these changes

2020-12-12 14:34 UTC, merged