96/default map on mobil
hochschule-darmstadt/einander-helfen pull request #254
Opened 2020-12-22 11:03 UTC by DianaPankratz

2020-12-22 15:52 UTC, MaiThiD requested changes
After I opened the map und scrolled down to the end of the page, the map automatically closes itself.

2021-01-13 14:45 UTC, FiedlerJan requested changes
Looks good, but please merge staging into this branch.

2021-01-13 17:04 UTC, LeDrieHda approved these changes

2021-01-13 17:26 UTC, MaiThiD approved these changes

2021-01-13 17:29 UTC, FiedlerJan approved these changes

2021-01-13 17:29 UTC, merged