#322/menu bug mobile
hochschule-darmstadt/einander-helfen pull request #376
Opened 2021-05-27 15:02 UTC by xcaverxiii

change menu icon size

close #322

2021-06-13 14:37 UTC, DianaPankratz requested changes
Because of the small padding at the top and bottom of the menu the first and last item seem to be bigger than the others. please remove the padding.

![image](https://user-images.githubusercontent.com/73997936/121811252-1f5e4600-cc64-11eb-8979-ab449dc4d3c9.png)

![image](https://user-images.githubusercontent.com/73997936/121811150-c55d8080-cc63-11eb-9124-c454134320eb.png)

And remove the padding on the right, too, as it looks weird when a page is selected: 
![image](https://user-images.githubusercontent.com/73997936/121811475-ce028680-cc64-11eb-842a-f84ab8e93e3f.png)

The burger menu should close automatically as soon as the user starts to scroll.

2021-06-17 09:48 UTC, xcaverxiii commented
> Because of the small padding at the top and bottom of the menu the first and last item seem to be bigger than the others. please remove the padding.

This padding comes from the vuetify menu. I removed it.

> And remove the padding on the right, too, as it looks weird when a page is selected:

This was a fail by me. Is fixed.
 
> The burger menu should close automatically as soon as the user starts to scroll.

This isn't anymore a part of this PR, because i don't know hot to do this. The related issue is still open.

2021-06-17 12:58 UTC, DianaPankratz approved these changes

2021-06-17 13:46 UTC, DianaPankratz commented
Please merge staging into this branch as the new page "Organisationen" needs an icon, too.

2021-06-24 09:42 UTC, merged