#365 fix location filter
hochschule-darmstadt/einander-helfen pull request #382
Opened 2021-05-30 14:09 UTC by xcaverxiii

fixed #365 

close #365

2021-05-30 15:07 UTC, DianaPankratz requested changes
The location filter works but now we have again the following problem: If you choose a country/city with enter, the search starts immediately but enter in this case should only set the county/city as the location. Only a secons preess on enter should start the search.

2021-05-30 17:23 UTC, xcaverxiii commented
> The location filter works but now we have again the following problem: If you choose a country/city with enter, the search starts immediately but enter in this case should only set the county/city as the location. Only a secons preess on enter should start the search.

now better?

2021-05-31 12:04 UTC, DianaPankratz commented
> > The location filter works but now we have again the following problem: If you choose a country/city with enter, the search starts immediately but enter in this case should only set the county/city as the location. Only a secons preess on enter should start the search.
> 
> now better?

Yes this works. 
But I just found another bug. The radius is not working correctly. If I choose a radius except "Überall" I will get results but I also get the message "Zu Ihrer Suchanfrage mit einem Radius von 5km haben wir keine Treffer gefunden. Folgende Ergebnisse werden in einem Umkreis von 25km gefunden."
The search itself is working. A lower radius will give me less results. But the message is not right,

![image](https://user-images.githubusercontent.com/73997936/120190501-fcba3f00-c218-11eb-81b9-e419f35d594b.png)

2021-06-02 08:20 UTC, xcaverxiii commented
> But I just found another bug. The radius is not working correctly. If I choose a radius except "Überall" I will get results but I also get the message "Zu Ihrer Suchanfrage mit einem Radius von 5km haben wir keine Treffer gefunden. Folgende Ergebnisse werden in einem Umkreis von 25km gefunden."
> The search itself is working. A lower radius will give me less results. But the message is not right,

I think this will be fixed after PR #383 is merged automatically. 
This is outside the scope of this issue. Wait for the merge and, if necessary, make a new issue.

2021-06-02 14:15 UTC, theErikss0n approved these changes
Ca be merged after the single comment is addressed.

2021-06-02 14:15 UTC, theErikss0n commented on app/src/components/search/LocationSearchBar.vue
> +      // this.$emit("enter", this.location);
Please remove this line of code if it is not needed anymore.

```suggestion
```

2021-06-02 15:59 UTC, DianaPankratz commented
I can't reproduce this bug so this is approved.

2021-06-02 15:59 UTC, DianaPankratz approved these changes

2021-06-02 16:01 UTC, merged