#292 seperate image cards as own component
hochschule-darmstadt/einander-helfen pull request #384
Opened 2021-06-02 08:48 UTC by xcaverxiii

create ImageCard component 

 close #292

2021-06-02 14:20 UTC, theErikss0n approved these changes

2021-06-03 16:53 UTC, KaiDrieHda requested changes
The cards now look like this:
![image](https://user-images.githubusercontent.com/73997608/120682474-c856b500-c49c-11eb-9793-a5d9554a156a.png)
Please make sure they are inline.

2021-06-05 09:59 UTC, xcaverxiii commented
> The cards now look like this:
> ...
> Please make sure they are inline.

@KaiDrieHda 
Dumb developer make stupid stings :D Is fixed.

2021-06-07 15:51 UTC, KaiDrieHda approved these changes

2021-06-07 15:55 UTC, merged