Add tracking
hochschule-darmstadt/einander-helfen pull request #385
Opened 2021-06-03 09:52 UTC by theErikss0n

This implements the usage of analytics in the client.
[Vue-Matomo](https://github.com/AmazingDreams/vue-matomo) is used in order to track site-urls and send those to our matomo server.
I extended our privacy notice with a declaration about matomo. The text is copied from OpenArtBrowser.

In order to only track in production and not during development or in staging, [vue modes](https://cli.vuejs.org/guide/mode-and-env.html#modes) and mode-specific env files are used.

@KaiDrieHda or @DianaPankratz can you please double check whether the privacy notice is all we need or if we need something else?

closes #339

2021-06-03 11:49 UTC, xcaverxiii approved these changes
looks ok

2021-06-04 11:23 UTC, theErikss0n commented
Together with @DianaPankratz we found out, that AdBlockers are blocking our opt-out i-frame provided by matomo.
I'm working on an alternative.
This should not be merged until this is resolved.

2021-06-04 15:33 UTC, DianaPankratz requested changes
Please change the info text for adblocker to something like: 

"Die Option zur Deaktivierung der Analyse ihrer Aktionen (Tracking) kann nicht angezeigt werden, da es von ihrem Browser blockiert wird. Möglicherweise blockiert ihr Browser ohnehin das Tracking, sodass Sie Ihr Einverständnis dafür hier nicht mehr entziehen müssen. Wenn Sie auf Nummer sicher gehen wollen, sollten Sie ihren AdBlocker deaktivieren und die Seite neu laden, um manuell die Erlaubnis zum Tracken zu entziehen."

Highlight this text by making it fat or in another color.

2021-06-06 11:54 UTC, xcaverxiii requested changes

2021-06-06 11:54 UTC, xcaverxiii commented on app/package.json
> +    "lint": "vue-cli-service lint",
the lint --max-warnings 0 --no fix got lost

2021-06-06 11:54 UTC, xcaverxiii commented on app/src/views/Privacy.vue
> +        <p v-if="!optOutIframeExists()">
dont use a function here, use a data attribute which is set by mounted or some other lifecycle hook.

2021-06-10 15:27 UTC, theErikss0n commented
The information, that adblock can block the i-frame is displayed all the time now.
It would not be worth the effort for now to only display it, if the i-frame is blocked.
It is not easy to implement it this way

2021-06-10 17:01 UTC, DianaPankratz requested changes
Please add a line break after the text. Currently in Opera it looks like this: 
![image](https://user-images.githubusercontent.com/73997936/121566923-4aefef00-ca1e-11eb-9873-8999a8c72667.png)

2021-06-17 08:37 UTC, DianaPankratz approved these changes

2021-06-17 08:38 UTC, xcaverxiii approved these changes

2021-06-17 08:39 UTC, merged