337/additional volunteer work providers
hochschule-darmstadt/einander-helfen pull request #394
Opened 2021-06-07 18:11 UTC by DianaPankratz

Adds a new page to the website that provides links to other volunteer work providers.

close #337

2021-06-08 19:21 UTC, KaiDrieHda approved these changes

2021-06-09 07:48 UTC, xcaverxiii requested changes

2021-06-09 07:48 UTC, xcaverxiii commented on app/src/views/Organizations.vue
> +<style>
add lang scss and use scoped css

2021-06-10 10:45 UTC, xcaverxiii commented on app/src/views/Organizations.vue
> +  column-count: 3;
maybe better us flex and vuetify standart css classes instead of custom css?

2021-06-17 10:04 UTC, xcaverxiii approved these changes

2021-06-17 12:00 UTC, merged