#402 fix reponsivnes of cards bug
hochschule-darmstadt/einander-helfen pull request #403
Opened 2021-06-11 14:42 UTC by xcaverxiii

close #402

2021-06-12 14:08 UTC, KaiDrieHda requested changes
In window width 960px to 1100 px the "Arbeit mit Jugendlichen"-card looks like this:
![image](https://user-images.githubusercontent.com/73997608/121778686-45b6af80-cb98-11eb-9dd6-edb6e7f39227.png)

Please make the font size smaller so the text stays inline and the white block is the same size as the other cards.

2021-06-13 14:46 UTC, DianaPankratz commented
> In window width 960px to 1100 px the "Arbeit mit Jugendlichen"-card looks like this:
> ![image](https://user-images.githubusercontent.com/73997608/121778686-45b6af80-cb98-11eb-9dd6-edb6e7f39227.png)
> 
> Please make the font size smaller so the text stays inline and the white block is the same size as the other cards.

I think the font-size itself is okay but the cards should jump into the new line earlier instead of shrinking them this far.

2021-06-17 09:35 UTC, KaiDrieHda approved these changes

2021-06-24 09:13 UTC, theErikss0n approved these changes

2021-06-24 09:44 UTC, merged