added alt atributes to all non decorativ images
hochschule-darmstadt/einander-helfen pull request #475
Opened 2021-11-10 14:51 UTC by Granoffel

2021-11-13 14:03 UTC, theErikss0n requested changes
The carousel alt-tags look good!

We should also add alt-tags for our image cards, as they are also non-decorative.

2021-11-13 14:03 UTC, theErikss0n commented on app/src/components/search/AreaSelect.vue
> +      <img class="areaImage" alt="areaImage" :src="item.img" />
"areaImage" is not descriptive. We should set the alt-tag to something like "Deutsche Flagge" and "Erdkugel" depending on the selectecd item.

2021-11-13 14:03 UTC, theErikss0n commented on app/src/components/search/AreaSelect.vue
> +      <img class="areaImageSelected" alt="areaImageSelected" :src="item.img" />
Like above, we should find a better fitting alt-tag.

2021-11-19 14:51 UTC, theErikss0n requested changes
Area select tags are good now!

We still need alt-tags for the image cards.

2021-11-24 07:32 UTC, Granoffel commented
The image cards a decorative. Image is set as background. Crawler recognise these as decorative.
Cards will be redesigned in #480

2021-11-24 09:48 UTC, theErikss0n approved these changes

2021-11-24 09:48 UTC, merged