#459 add meta fragment for better crawling
hochschule-darmstadt/einander-helfen pull request #477
Opened 2021-11-10 17:33 UTC by Granoffel

TODO: Find Keywords #465 
and add an meta description to each page

- Anbieter
- Über Uns

2021-11-13 14:18 UTC, theErikss0n requested changes
I'd say this is ok in order to find out, whether the meta tags have an impact on SEO checkers.
We have to open an issue for adding an actual meaningful description though, as the current does not describe what our site does.

2021-11-13 14:18 UTC, theErikss0n commented on app/public/index.html
> +    <meta name="description" lang="de" content="Einander Helfen: ehrenamtliche Tätigkeit, fsj und föj sowie volunteering, betreuung und thw" />
```suggestion
    <meta name="description" lang="de" content="Einander Helfen: ehrenamtliche Tätigkeit, fsj und föj, sowie volunteering, Betreuung und THW" />
```

2021-11-24 07:26 UTC, Granoffel commented
Issue #485 add actual meaningful Meta description is now open.
As proposed this is now an meta tag test issue.

2021-11-24 09:32 UTC, theErikss0n approved these changes

2021-11-24 09:32 UTC, merged